theme: jekyll-theme-midnight
plugins:
  - jekyll-relative-links
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - class-01.md
  - CareerLaunchStrategy.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md